### ISSUE TITLE
Strange string disappeared

### ISSUE THREAD

**Issue by groony** [ne1ro/siteshot#5]
@ne1ro When you bump version this string disappeared from siteshot.js

```
#!/usr/bin/env node
```

**Comment by ne1ro** [comment]
Where this disappeared? It's still exist in `master` branch: https://github.com/ne1ro/siteshot/blob/master/siteshot.js#L1

**Comment by groony** [comment]
Here i don't see it https://github.com/ne1ro/siteshot/tree/release/0.1.1

**Comment by ne1ro** [comment]
ok, fixed.

**Comment by groony** [comment]
sorry it's disapered after coffee compile to js) please add again)
